services:
  database:
    image: gvenzl/oracle-xe:21-slim-faststart
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=${DB_PASSWORD}
    volumes:
      - oracledata:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "pgrep", "tnslsnr"]
      interval: 10s
      timeout: 5s
      retries: 50

  backend:
    build:
      context: ./backend
    container_name: python-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/__pycache__ # evita conflito com cache local
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  oracledata:
